### ISSUE TITLE
Is it possible to render without ARSCNView?

### ISSUE THREAD

**Issue by stayHF** [svtek/SceneKitVideoRecorder#35]
First, thanks for the great work of this repo.

I want to render ar content, and apply some custom image filters(such as style filter，color adjust filter etc). When use ARSCNView, I have no choice to do it.

Now, I load 3D model by using SCNScene, and can render 3D model using SCNRender.
But don't know how to apply  camera transform to the scene. 

Thank you very much for any suggest!

**Comment by okaris** [comment]
Hello and thank you @stayHF .

This issue is outside the scope of the project. However I would like to try and help you if you can describe how do you achieve the filters using SCNScene and how they are not working with ARSCNView. 

I am afraid without an ARSCNView (and with only SCNScene) you cannot get world tracking. If you can absolutely not apply the filters to ARSCNView, you might want to use Metal. With Metal you can seperately handle rendering and world tracking. And Metal is really performant when it comes to effects, filters and any graphics related computations.

I am closing this issue but please respond here so we can try to help.

**Comment by stayHF** [comment]
This issue is inside the scope of this project and snapshot is inefficient, not perfect.
When use ARSCNView, you can not apply filters to the background image that camera captured.
After some research, I found if we can use this graph:
ARSession->GPUImageFilterChain->3DModelFilter(SCNScene+SCNRenderer) ->AVAssetWriter.
it will be awesome!!!

Now I complete the 3DModelFilter, but do not know how to apply ARCamra's transfrom to SCNScene.  may be we can do it together.
